// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import FireMissileReducer from "../fire_missile_reducer";
import RegisterPlayerReducer from "../register_player_reducer";
import SetWaypointReducer from "../set_waypoint_reducer";
import SpawnShipReducer from "../spawn_ship_reducer";
import ToggleRadarReducer from "../toggle_radar_reducer";

export type FireMissileParams = __Infer<typeof FireMissileReducer>;
export type RegisterPlayerParams = __Infer<typeof RegisterPlayerReducer>;
export type SetWaypointParams = __Infer<typeof SetWaypointReducer>;
export type SpawnShipParams = __Infer<typeof SpawnShipReducer>;
export type ToggleRadarParams = __Infer<typeof ToggleRadarReducer>;

