// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ownerId: __t.identity().name("owner_id"),
  x: __t.f32(),
  y: __t.f32(),
  heading: __t.f32(),
  speed: __t.f32(),
  targetX: __t.f32().name("target_x"),
  targetY: __t.f32().name("target_y"),
  targetShipId: __t.option(__t.u64()).name("target_ship_id"),
});
